
server:
  port: 8990

#spring:
#
#  application:
#    name: Login
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/JDBC
#    username: postgres
#    password: postgres
#
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    hibernate:
#      ddl-auto: update
#
#    show-sql: false
#    open-in-view: true